### ISSUE TITLE
处理内联样式时的问题

### ISSUE THREAD

**Issue by Dxxxxxxww** [youncccat/postcss-relaxed-unit#6]
当一个公共组件的宽高需要从使用层传入的话，就有点僵硬了。举个🌰：

`
// 这是一个 ListItem
<div class="item value" :style="valueStyle">{{ value }}</div>

  props: {
    valueWidth: String
  },
  computed: {
    valueStyle() {
      const ret = {
        width: '204px'
      }
      if (this.valueWidth) {
        ret.width = this.valueWidth
      }
      return ret
    }
  }
`
如果在父级使用的话，传入宽度的单位就只能是 px 或者是 rem，而不能是自定义单位

**Comment by Dxxxxxxww** [comment]
` <div class="item value" :style="valueStyle">{{ __value }}</div>`

**Comment by youncccat** [comment]
postcss 只会处理单独的 css 文件，inline style 一般由框架处理。可直接使用 [postcss-js](https://github.com/postcss/postcss-js) 将 inline style 进行转换后传入

**Comment by Dxxxxxxww** [comment]
@youncccat 根据自己在 postcss.config 里配置的规则，计算后放到 inline style 呗，是这个意思不
